project: 
  type: website

website:
  title: "Tam Tran - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/Tam-Tran-24002/datascience_portfolio
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Tam Tran 2025Â©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/tam-tran-b37a9123b/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "SQL projects"
        file: SQL.qmd
      - text: "Machine Learning"
        file: machine_mearning.qmd
      - text: "Data Science Programming projects"
        file: data_science_programming.qmd
      - text: "Machine Learning"
        file: ml.qmd
  
  # learn more about navication here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Data Science Programming"
      style: "docked"
      background: light
      contents:
        - text: "Data Science Programming projects"
          file: data_science_programming.qmd
        - text: "---"
        - text: "Project 1"
          file: Data Science Programming projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Data Science Programming projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Data Science Programming projects/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Data Science Programming projects/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Data Science Programming projects/project5.qmd
        - text: "---"
    - title: "SQL projects"
      style: "docked"
      background: light
      contents:
        - text: "SQL projects"
          file: SQL.qmd
        - text: "---"
        - text: "Introduction"
          file: SQL projects/Git Version Control.txt
        - text: "---"
        - text: "Forward Engineering"
          file: SQL projects/operating_systems_forward_engineer.sql
        - text: "---"
        - text: "Rows"
          file: SQL projects/operating_systems_rows.sql
        - text: "---"
        - text: "Materials"
          file: SQL projects/Turn-in Materials
        - text: "---"
        - text: "SQL MWB"
          file: SQL projects/operating_systems.mwb
        - text: "---"
    - title: "Story Telling"
      style: "docked"
      background: light
      contents:
        - text: "Story Telling"
          file: story_telling.qmd
        - text: "---"
        - text: "Project 1"
          file: Story_Telling/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Story_Telling/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Story_Telling/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Story_Telling/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Story_Telling/project5.qmd
        - text: "---"
    - title: "Machine Learning"
      style: "docked"
      background: light
      contents:
        - text: "Machine Learning"
          file: ml.qmd
        - text: "---"
        - text: "Project 1"
          file: Machine_Learning/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Machine_Learning/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Machine_Learning/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Machine_Learning/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Machine_Learning/project5.qmd
        - text: "---"
  
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



